from pathlib import Path
import csv, json, math, zipfile, os, re, shutil
from collections import Counter, defaultdict

ROOT=Path('/mnt/data/phase_tao_close_read')
NOTES=ROOT/'notes'
ORTH=Path('/mnt/data/orthad_walk_extract/orthad_corrected_carried_walk_depth6_20260620T113500')

def read_csv(path):
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def write_csv(path, rows, fieldnames=None):
    if fieldnames is None:
        keys=[]
        for r in rows:
            for k in r.keys():
                if k not in keys: keys.append(k)
        fieldnames=keys
    with open(path,'w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fieldnames)
        w.writeheader(); w.writerows(rows)

def comp(s):
    return ''.join('1' if c=='0' else '0' for c in s)

def rev(s):
    return s[::-1]

def hamming(a,b):
    return sum(x!=y for x,y in zip(a,b))

# --- Wilhelm Klein group / involution analysis ---
kw = read_csv(ROOT/'iching_wilhelm_kingwen_pair_operations_v2.csv')
pair_rows=[]
for row in kw:
    odd=int(row['odd_hex']); even=int(row['even_hex'])
    s=row['odd_binary']; t=row['even_binary']
    R=rev(s); C=comp(s); RC=rev(comp(s))
    matches=[]
    for name,val in [('I',s),('R',R),('C',C),('RC',RC)]:
        if t==val: matches.append(name)
    palindrome=(s==R)
    anti_palindrome=(R==C)
    if matches==['R']:
        op_class='R_only_vertical_reversal'
    elif set(matches)=={'R','C'}:
        op_class='anti_palindrome_R_equals_C'
    elif set(matches)=={'C','RC'}:
        op_class='palindrome_C_equals_RC'
    elif matches==['C']:
        op_class='C_only_full_complement'
    elif matches==['RC']:
        op_class='RC_only_reverse_complement'
    else:
        op_class='other_or_multi'
    pair_rows.append({
        'odd_hex': odd,
        'even_hex': even,
        'odd_binary': s,
        'even_binary': t,
        'odd_english': row['odd_english'],
        'even_english': row['even_english'],
        'matches': '+'.join(matches),
        'operation_class': op_class,
        'is_palindrome_under_R': str(palindrome).lower(),
        'is_antipalindrome_R_equals_C': str(anti_palindrome).lower(),
        'hamming_odd_to_even': hamming(s,t),
        'hamming_odd_to_R': hamming(s,R),
        'hamming_odd_to_C': hamming(s,C),
        'R_of_odd': R,
        'C_of_odd': C,
        'RC_of_odd': RC,
        'terminal_pair_flag': str(odd in (1,63) or even in (2,64)).lower(),
        'bridge_reading': (
            'pair generated inside finite carrier by involution group; scalar ordinal is not the transition law'
        )
    })
write_csv(ROOT/'wilhelm_kingwen_klein_involution_pair_analysis.csv', pair_rows)

class_counts=Counter(r['operation_class'] for r in pair_rows)
match_counts=Counter(r['matches'] for r in pair_rows)
hamming_counts=Counter(str(r['hamming_odd_to_even']) for r in pair_rows)
summary_rows=[]
for cls,count in class_counts.items():
    examples=[f"{r['odd_hex']}/{r['even_hex']} {r['odd_english']}->{r['even_english']}" for r in pair_rows if r['operation_class']==cls][:8]
    summary_rows.append({
        'operation_class':cls,
        'pair_count':count,
        'fraction_of_32_pairs':round(count/32,4),
        'examples':' | '.join(examples),
        'bridge_status': 'strong carrier-operation evidence' if cls!='other_or_multi' else 'red-team required'
    })
write_csv(ROOT/'wilhelm_kingwen_klein_involution_class_summary.csv', summary_rows)

# special boundary/stabilizer rows
special_rows=[]
for r in pair_rows:
    if r['operation_class']!='R_only_vertical_reversal' or r['terminal_pair_flag']=='true':
        special_rows.append({
            'pair': f"{r['odd_hex']}-{r['even_hex']}",
            'names': f"{r['odd_english']} / {r['even_english']}",
            'odd_binary': r['odd_binary'],
            'even_binary': r['even_binary'],
            'operation_class': r['operation_class'],
            'structural_reason': (
                'odd carrier is palindrome so complement and reverse-complement collapse' if r['operation_class']=='palindrome_C_equals_RC' else
                'odd carrier is anti-palindrome so reversal and complement collapse' if r['operation_class']=='anti_palindrome_R_equals_C' else
                'terminal anchor included for cycle/readout inspection'
            ),
            'orthad_bridge_reading': 'finite carrier has internal symmetry/stabilizer; readout pair is generated by carrier operation, not scalar adjacency alone'
        })
write_csv(ROOT/'wilhelm_kingwen_boundary_stabilizer_pairs.csv', special_rows)

# --- Orthad corrected walk invariants ---
primitive=(ORTH/'output_data/20260620T113500_primitive_word.txt').read_text().strip()
laps=read_csv(ORTH/'output_data/20260620T113500_lap_summaries.csv')
seats=read_csv(ORTH/'output_data/20260620T113500_carried_seats.csv')

op_counts=Counter(primitive)
# parse q pairs
def parse_pair(s):
    nums=re.findall(r'\d+', s)
    return tuple(map(int,nums[:2]))
seat_pairs=[parse_pair(r['q_pair']) for r in seats]
uvs=[int(r['uv']) for r in seats]
# verify Fibonacci recurrence over pairs: next pair=(v,u+v)
fib_ok=True; bad=[]
for i in range(len(seat_pairs)-1):
    u,v=seat_pairs[i]
    exp=(v,u+v)
    if seat_pairs[i+1]!=exp:
        fib_ok=False; bad.append((i+1,seat_pairs[i],seat_pairs[i+1],exp))
lap_rows=[]
prev_uv=None
for l in laps:
    lap=int(l['lap_index'])
    q_start=tuple(map(int,re.findall(r'\d+',l['q_start'])[:2]))
    q_comp=tuple(map(int,re.findall(r'\d+',l['q_completion'])[:2]))
    uv=int(l['uv_completion'])
    theta0=int(l['theta_quarters_start']); thetaL=int(l['theta_quarters_at_L'])
    lap_rows.append({
        'lap_index':lap,
        'depth_after_L':int(l['depth_after_L']),
        'q_start':str(q_start),
        'q_completion':str(q_comp),
        'uv_completion':uv,
        'uv_growth_from_prior_lap': '' if prev_uv is None else round(uv/prev_uv,12),
        'theta_quarters_start':theta0,
        'theta_quarters_at_L':thetaL,
        'theta_quarter_increment':thetaL-theta0,
        'rank_after_L_expected':int(l['depth_after_L'])+1,
        'six_BQ_seats_confirmed':str(len(re.findall(r'\d+',l['support_seats']))==6).lower(),
        'signed_position_list':l['signed_position_list'],
        'phase_factor_list':l['phase_factor_list']
    })
    prev_uv=uv
write_csv(ROOT/'orthad_corrected_walk_invariant_audit.csv', lap_rows)

orthad_invariants={
    'primitive_word_length':len(primitive),
    'primitive_counts':dict(op_counts),
    'expected_counts':{'B':36,'Q':36,'L':6},
    'counts_match_expected': dict(op_counts)=={'B':36,'Q':36,'L':6},
    'seat_count':len(seats),
    'lap_count':len(laps),
    'fib_pair_recurrence_ok':fib_ok,
    'fib_pair_bad_examples':bad[:5],
    'theta_lap_increments': [r['theta_quarter_increment'] for r in lap_rows],
    'all_theta_lap_increments_6': all(r['theta_quarter_increment']==6 for r in lap_rows),
    'rank_after_final_L': int(lap_rows[-1]['rank_after_L_expected']),
    'final_q': lap_rows[-1]['q_completion'],
    'final_uv': lap_rows[-1]['uv_completion']
}
(ROOT/'orthad_corrected_walk_invariant_audit.json').write_text(json.dumps(orthad_invariants,indent=2),encoding='utf-8')

# --- Unified automata normal form / validation gate ---
anc=read_csv(ROOT/'ancient_yi_64_lsd_first_successor_table.csv')
yi_internal=sum(1 for r in anc if r['event']=='internal_successor')
yi_lift=sum(1 for r in anc if 'cycle_completion' in r['event'])
wilhelm_graph=read_csv(ROOT/'iching_wilhelm_single_line_flip_graph.csv')
line_prof=read_csv(ROOT/'iching_wilhelm_line_position_operational_profile.csv')
mfe=read_csv(ROOT/'mfe_orthad_custody_flow.csv')

def status(ok,strong='PASS_STRONG',weak='OPEN'):
    return strong if ok else weak
normal_rows=[
    {
        'corpus':'Corrected Orthad carried walk',
        'retained_carrier':'Xi_hat state with q, theta, rank/latches, primitive word',
        'alphabet_or_operator':'Q/B/L; realized as (BQ)^6 L per lap',
        'transition_evidence':f"primitive counts {dict(op_counts)}; {len(seats)} emitted BQ seats; fib recurrence ok={fib_ok}",
        'completion_event':'six BQ seats complete lap/domain; L emitted',
        'lift_or_rechart':'L carries q and theta, rank grows by one',
        'readout':'Orthad lens/channel table reads after emitted walk exists',
        'scalar_terminal':'Shadow residual remains external comparison',
        'gate_status':'ANCHOR_REFERENCE'
    },
    {
        'corpus':'Ancient Yi octal place carrier',
        'retained_carrier':'LSD-first octal place-symbol / line-symbol carrier',
        'alphabet_or_operator':'successor/carry over base-8 place positions',
        'transition_evidence':f"{len(anc)} two-place states; {yi_internal} internal successors; {yi_lift} completion carry event in 0..63 table",
        'completion_event':'77 = 8^2-1 completes two-place domain',
        'lift_or_rechart':'77 -> 001 opens three-place domain',
        'readout':'same retained carrier read as octal and decimal; earlier tables also binary',
        'scalar_terminal':'decimal number depends on digit-order convention',
        'gate_status':'PASS_STRONG_OPERATIONAL_BRIDGE'
    },
    {
        'corpus':'Wilhelm I Ching six-line carrier',
        'retained_carrier':'64 retained six-line binary states',
        'alphabet_or_operator':'single-line flips plus King Wen pair involutions R,C,RC',
        'transition_evidence':f"{len(wilhelm_graph)} directed single-line flips; 32 adjacent pairs all classified by finite involution group",
        'completion_event':'top-line and pair-boundary semantics mark excess/return/cycle candidates',
        'lift_or_rechart':'not closed; candidate via line-position ladder and terminal pair 63/64',
        'readout':'hexagram number/name/text are projections of six-line carrier',
        'scalar_terminal':'King Wen ordinal is not the transition law',
        'gate_status':'PASS_STRONG_FOR_CARRIER_TRANSFORM; LIFT_OPEN'
    },
    {
        'corpus':'MFE/Liu2022 code bridge',
        'retained_carrier':'full 3D MHD field arrays with boundary/ghost-zone state',
        'alphabet_or_operator':'boundary callbacks, ideal RHS, nonideal/conduction RHS, RK update',
        'transition_evidence':f"{len(mfe)} custody-flow stages; module/subroutine/call inventories available",
        'completion_event':'boundary/ghost/edge completion before evolution step is admissible',
        'lift_or_rechart':'physical re-chart/topological lift remains data-dependent',
        'readout':'outputs/synthetic diagnostics after state evolution',
        'scalar_terminal':'AIA/figures are projections, not carried state',
        'gate_status':'PASS_STRONG_FOR_CUSTODY; TOPOLOGY_DATA_OPEN'
    }
]
write_csv(ROOT/'bridge_operational_automata_normal_form_v1.csv', normal_rows)

gate_rows=[]
gates=['retained_carrier','admissible_transition','refinement_operator','completion_boundary','lift_or_rechart','readout_after_state','scalar_terminal_discipline','invariant_custody']
evidence={
    'Corrected Orthad carried walk': {
        'retained_carrier':'PASS','admissible_transition':'PASS','refinement_operator':'PASS','completion_boundary':'PASS','lift_or_rechart':'PASS','readout_after_state':'PASS','scalar_terminal_discipline':'PASS','invariant_custody':'PASS_OPEN_FORMAL_PROOF_SURFACE'
    },
    'Ancient Yi octal place carrier': {
        'retained_carrier':'PASS','admissible_transition':'PASS','refinement_operator':'PASS_MODULAR_B_CANDIDATE','completion_boundary':'PASS','lift_or_rechart':'PASS','readout_after_state':'PASS','scalar_terminal_discipline':'PASS','invariant_custody':'OPEN_DIGIT_ORDER_TRANSLATION_PROOF'
    },
    'Wilhelm I Ching six-line carrier': {
        'retained_carrier':'PASS','admissible_transition':'PASS','refinement_operator':'PASS_MODULAR_B_CANDIDATE','completion_boundary':'PARTIAL_TOP_LINE_TERMINAL_EVIDENCE','lift_or_rechart':'OPEN','readout_after_state':'PASS','scalar_terminal_discipline':'PASS','invariant_custody':'PASS_CARRIER_INVOLUTION_GROUP'
    },
    'MFE/Liu2022 code bridge': {
        'retained_carrier':'PASS','admissible_transition':'PASS','refinement_operator':'PASS_PHYSICAL_OPERATOR_SPLIT','completion_boundary':'PASS_BOUNDARY_GHOST_COMPLETION','lift_or_rechart':'OPEN_DATA_DEPENDENT_TOPOLOGY','readout_after_state':'PASS','scalar_terminal_discipline':'PASS','invariant_custody':'OPEN_CONSERVATION_DATA_REQUIRED'
    }
}
for corpus, gs in evidence.items():
    for gate in gates:
        gate_rows.append({'corpus':corpus,'gate':gate,'status':gs[gate]})
write_csv(ROOT/'bridge_gate_pass_fail_matrix_v44.csv', gate_rows)

# Kill tests / blockers
kill_rows=[
    {'claim':'Ancient Yi exact-B identity','kill_or_confirm_test':'extract full 64-row line-order table and prove successor/carry law over retained carrier; compare with arbitrary-start Phase B, not only origin Fibonacci path','current_status':'NOT_CLOSED; modular-B candidate remains strong'},
    {'claim':'Wilhelm ordinal sequence is transition law','kill_or_confirm_test':'show adjacent pairs require scalar ordinal only; current finite involution analysis refutes scalar-only reading','current_status':'SCALAR_ONLY_READING_WEAKENED'},
    {'claim':'L/re-chart bridge is just metaphor','kill_or_confirm_test':'for each corpus identify explicit completion condition and carried invariant across new domain/chart/lap','current_status':'PASS for Orthad and Ancient Yi; PASS_CANDIDATE for Yin-Yang/MFE; OPEN for Wilhelm'},
    {'claim':'MFE/Liu readout is carried object','kill_or_confirm_test':'trace output/synthetic diagnostic after state arrays and boundary/RHS evolution','current_status':'REFUTED by custody-flow inventory'},
    {'claim':'Shadow residual is loaded into Orthad lift','kill_or_confirm_test':'inspect corrected carried walk channel table and external comparison outputs','current_status':'REFUTED; Shadow remains external reference'},
]
write_csv(ROOT/'bridge_kill_tests_and_next_evidence_v44.csv', kill_rows)

# Integration summary JSON
summary={
    'version':'v44',
    'new_pass':'50_WILHELM_KLEIN_INVOlUTION_AND_OPERATIONAL_NORMAL_FORM_PASS',
    'core_findings':[
        'King Wen adjacent pairs are generated by finite carrier involutions R, C, RC; 0 of 32 adjacent pairs require scalar ordinal adjacency as the transition law.',
        'The exceptions to reverse-only pairing are exactly symmetry/stabilizer collapses: palindromic carriers where C=RC, and anti-palindromic carriers where R=C.',
        'Corrected Orthad invariants were rechecked from the zip: 36 B, 36 Q, 6 L; six BQ seats per lap; Fibonacci carried-pair recurrence; theta advances six quarters per lap; final rank 7.',
        'The corpus can now be represented in one operational automata normal form across Orthad, Ancient Yi, Wilhelm, and MFE/Liu.',
    ],
    'coverage':{
        'paper_resource_first_pass':'~94.5%',
        'code_data_bridge':'~90%',
        'overall_project_research_pass':'~87.5%'
    },
    'orthad_invariants':orthad_invariants,
    'wilhelm_operation_class_counts':dict(class_counts),
    'wilhelm_match_counts':dict(match_counts),
    'wilhelm_hamming_counts':dict(hamming_counts),
    'open_blockers':[
        'Ancient Yi full translation and line-order confirmation.',
        'Latest active Phase selector/floor source from HDD.',
        'Dongyuan/Ceyuan diagram-to-formula state graph.',
        'Liu2022 QSL/current/connectivity time series.',
        'Formal modular-B operator-family theorem and negative controls.',
    ]
}
(ROOT/'bridge_research_progress_summary_v44.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')

# New note 50
note = f"""# 50. Wilhelm Klein involution and operational normal-form pass

## Scope

This pass makes new progress on the operational bridge rather than adding only a correction note. It extends the Wilhelm/Yi line by testing the King Wen adjacent-pair structure as a finite carrier-operation system and then reunifies Orthad, Ancient Yi, Wilhelm, and MFE/Liu into one operational automata normal form.

## New artifacts

- `wilhelm_kingwen_klein_involution_pair_analysis.csv`
- `wilhelm_kingwen_klein_involution_class_summary.csv`
- `wilhelm_kingwen_boundary_stabilizer_pairs.csv`
- `orthad_corrected_walk_invariant_audit.csv`
- `orthad_corrected_walk_invariant_audit.json`
- `bridge_operational_automata_normal_form_v1.csv`
- `bridge_gate_pass_fail_matrix_v44.csv`
- `bridge_kill_tests_and_next_evidence_v44.csv`
- `bridge_research_progress_summary_v44.json`

## Main new finding

The Wilhelm King Wen adjacent-pair structure is not scalar-adjacent noise. It is generated by a small finite carrier-operation algebra on the retained six-line state.

For each odd/even adjacent pair, the odd six-line carrier `s` was tested against:

```text
I(s)  = s
R(s)  = reverse(s)
C(s)  = complement(s)
RC(s) = reverse(complement(s))
```

Result:

```text
R_only_vertical_reversal: {class_counts.get('R_only_vertical_reversal',0)} pairs
anti_palindrome_R_equals_C: {class_counts.get('anti_palindrome_R_equals_C',0)} pairs
palindrome_C_equals_RC: {class_counts.get('palindrome_C_equals_RC',0)} pairs
other_or_unclassified: {class_counts.get('other_or_multi',0)} pairs
```

All 32 adjacent pairs are explained by retained-carrier involutions.

This is a stronger result than the previous count of reverse/complement pair types because it identifies the exceptional cases as stabilizer collapses of the same finite operation family:

```text
palindrome under R:
  C(s) = RC(s)

anti-palindrome where R(s)=C(s):
  reversal and complement collapse to the same output
```

## Why this matters

The King Wen ordinal is not the transition law. The transition law is carried by the six-line object and finite operations on it. The scalar sequence is a readout/index layered over the retained carrier.

This directly supports the project spine:

```text
retained carrier first
-> admissible carrier operation
-> pair/readout relation
-> scalar ordinal last
```

## Corrected Orthad invariant recheck

The corrected carried-walk zip was rechecked directly from its output data.

```json
{json.dumps(orthad_invariants, indent=2)}
```

The recheck confirms the reference anchor used by the bridge-control document:

```text
primitive grammar: Q/B/L
lap/domain: (BQ)^6 L
depth 6: ((BQ)^6 L)^6
B continues after every L
L carries q and theta
rank grows by exactly one per L
Orthad reads after the emitted walk exists
Shadow Residual remains external to the lift
```

## Operational automata normal form

The research now has a reusable normal form across four different classes of corpus:

| Corpus | Retained carrier | Operation | Completion | Lift/readout status |
|---|---|---|---|---|
| Corrected Orthad | `Xi_hat`, q, theta, word | `(BQ)^6 L` | six seats per lap | L carries q/theta; Orthad reads after walk |
| Ancient Yi | LSD-first octal/line carrier | successor/carry | `8^k - 1` | new high-place domain opens |
| Wilhelm | six-line carrier | single-line flips; R/C/RC involutions | terminal/top-line candidates | readout strong; lift partly open |
| MFE/Liu | full 3D MHD field state | boundary/RHS/nonideal/RK | ghost/boundary completion | diagnostics after state evolution |

This makes the bridge more falsifiable because the comparison target is no longer a vague analogy. Each corpus must be tested against the same gates:

```text
retained carrier
admissible transition
refinement/operator law
completion boundary
lift/re-chart
readout after state
scalar-terminal discipline
invariant custody
```

## Bridge status after v44

```text
Ancient Yi retained carrier/readout: STRONG_OPERATIONAL_BRIDGE
Ancient Yi finite completion/carry/lift: STRONG_OPERATIONAL_BRIDGE
Ancient Yi B-like refinement: STRONG_MODULAR_B_CANDIDATE / NOT_EXHAUSTED
Wilhelm carrier-operation algebra: STRONG_OPERATIONAL_BRIDGE
Wilhelm L/re-chart: OPEN, with top-line/terminal candidates
MFE/Liu retained-state custody: STRONG_OPERATIONAL_BRIDGE
MFE/Liu topology/lift: OPEN pending QSL/current/connectivity data
```

## Current understanding

Phase Calculus is being tested as a primitive discrete framework that may normalize external systems by function:

```text
retained state
-> admissible operation
-> carrier-specific refinement arithmetic
-> completion / blockage / threshold
-> carry / lift / re-chart
-> boundary readout
-> scalar only as terminal projection
-> invariant/custody preservation
```

The strongest current research result is that several external systems now preserve this stack operationally without needing identical terminology or identical arithmetic.

## Latest revealing findings

1. The Wilhelm King Wen pair structure is generated by finite line-carrier involutions, not by scalar ordinal adjacency alone.
2. The exceptional King Wen pairs are not irregular residue; they are symmetry/stabilizer cases of the same operation family.
3. Corrected Orthad and Ancient Yi now form two clean growth-law anchors:
   - Orthad: six BQ seats then L; rank +1; q/theta carried.
   - Ancient Yi: `8^k - 1` completion then high-place carry/lift.
4. MFE/Liu remains a separate physical bridge: retained field state plus boundary custody plus ideal/nonideal evolution before diagnostic projection.
5. Modular-B is now a real research program: B-like refinement can be studied as a carrier-selected operator family, not as a rigid semantic clone of the canonical origin-path B corridor.

## Progress estimate

```text
paper/resource first-pass coverage: ~94.5%
code/data bridge coverage: ~90%
overall project research pass: ~87.5%
```

## Next blockers

```text
1. Ancient Yi full translation and line-order proof.
2. Latest active Phase selector/floor source from HDD.
3. Dongyuan/Ceyuan diagram-to-formula state graph.
4. Liu2022 QSL/current/connectivity time series.
5. Formal modular-B operator-family theorem with negative controls.
```
"""
(NOTES/'50_WILHELM_KLEIN_INVOLUTION_AND_OPERATIONAL_NORMAL_FORM_PASS.md').write_text(note, encoding='utf-8')

# Update live notes and mechanism ledger concisely
live=NOTES/'01_LIVE_NOTES.md'
with open(live,'a',encoding='utf-8') as f:
    f.write("""

## v44 update: Wilhelm carrier involution + operational normal form

New pass `50_WILHELM_KLEIN_INVOLUTION_AND_OPERATIONAL_NORMAL_FORM_PASS.md` adds a finite carrier-operation analysis of King Wen adjacent pairs.

Main lock: all 32 odd/even King Wen adjacent pairs are generated by retained six-line carrier involutions R, C, and RC. The exceptional cases are symmetry/stabilizer collapses, not unstructured residue. This strengthens retained-carrier-before-scalar-readout discipline.

The active bridge normal form is now:

retained carrier -> admissible transition -> carrier-specific refinement/operator law -> completion boundary -> lift/re-chart -> readout after state -> scalar-terminal projection -> invariant custody.
""")
mech=NOTES/'04_MECHANISM_LEDGER.md'
with open(mech,'a',encoding='utf-8') as f:
    f.write("""

## v44 mechanism lock: King Wen finite involution algebra

Carrier: retained six-line binary state.

Operations tested:
- I: identity
- R: vertical reversal
- C: line complement
- RC: reverse complement

Finding: every odd/even King Wen adjacent pair is explained by R/C/RC carrier operations. Most are R-only. The non-R-only cases are exactly palindrome or anti-palindrome stabilizer collapses where C=RC or R=C.

Bridge role: strong retained-carrier transition/readout bridge; not an exact Phase B proof; useful modular-B operator-family evidence.
""")
# Update coverage rows if present
cov_path=ROOT/'coverage_percent_status.csv'
cov=read_csv(cov_path)
# append/update synthetic rows
for row in cov:
    if row.get('resource','')=='source/code/iching-wilhelm-dataset-master/data/i-ching-basic.js':
        row['coverage_percent']='97'
        row['status']='transition graph + finite involution pair algebra complete; full textual translation semantics still open'
    if row.get('resource','')=='Phase package formal/Lean/SymPy/scripts broad pass':
        row['coverage_percent']='78'
        row['status']='verification surface indexed; bridge gate matrix and operational normal form added; execution audit not complete'
# if schema unknown, preserve fields
write_csv(cov_path,cov,fieldnames=list(cov[0].keys()) if cov else None)

# Update progress index
progress=(ROOT/'CURRENT_PROGRESS_INDEX.md')
progress.write_text(f"""# Current Progress Index

## Latest package

`phase_tao_close_read_notes_v44.zip`

## Latest pass

`notes/50_WILHELM_KLEIN_INVOLUTION_AND_OPERATIONAL_NORMAL_FORM_PASS.md`

## Latest revealing finding

The Wilhelm King Wen adjacent-pair relation is generated by finite operations on the retained six-line carrier:

```text
R(s)  = reverse(s)
C(s)  = complement(s)
RC(s) = reverse(complement(s))
```

All 32 odd/even adjacent pairs are explained by this operation family. The exceptional pairs are symmetry/stabilizer collapses:

```text
palindrome:      C(s)=RC(s)
anti-palindrome: R(s)=C(s)
```

This strengthens the retained-carrier-before-scalar-readout bridge and turns Wilhelm into a real finite carrier-operation bridge, not just a table of symbolic names.

## Current bridge spine

```text
retained carrier/state
-> admissible transition
-> carrier-specific refinement/operator law
-> completion / blockage / threshold
-> carry / lift / re-chart
-> boundary readout
-> scalar only as terminal projection
-> invariant/custody preservation
```

## Current progress estimate

```text
paper/resource first-pass coverage: ~94.5%
code/data bridge coverage: ~90%
overall project research pass: ~87.5%
```

## Highest-value open blockers

1. Ancient Yi full translation and line-order proof.
2. Latest active Phase selector/floor source from HDD.
3. Dongyuan/Ceyuan diagram-to-formula state graph.
4. Liu2022 QSL/current/connectivity time series.
5. Formal modular-B operator-family theorem with negative controls.
""", encoding='utf-8')

# create clean zip excluding renders/tmp/images/PDFs/zips/cache/make scripts
zip_path=Path('/mnt/data/phase_tao_close_read_notes_v44.zip')
exclude_dirs={'renders','tmp','__pycache__'}
exclude_ext={'.png','.jpg','.jpeg','.gif','.webp','.pdf','.zip'}
with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED) as z:
    for p in ROOT.rglob('*'):
        if not p.is_file(): continue
        rel=p.relative_to(ROOT)
        if any(part in exclude_dirs for part in rel.parts): continue
        if p.suffix.lower() in exclude_ext: continue
        if p.name.startswith('.make_'): continue
        z.write(p, Path('phase_tao_close_read')/rel)
print(zip_path)
