from pathlib import Path
import csv, nbformat
from nbformat.v4 import new_notebook,new_markdown_cell,new_code_cell
# Source notebook is generated by scripts/20260711T162758_rebuild.py from packaged source-bound rows.
print("Use 20260711T162758_rebuild.py")
