#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, hashlib, json
from pathlib import Path
from fractions import Fraction
import sympy as sp

TS='20260711T145605'
FIRST_WORD='BQQBBBQBQBBQBBL'


def capacity(j:int)->int:
    if j==1:return 2
    if j==2:return 4
    return 2**(2*j)


def j_start(A:int)->int:
    return 1+6*(2**A-1)


def can_b(A:int,u:int,v:int,k:int,j:int)->bool:
    N=6*(2**A)
    if k<N-1:
        nu,nv=v,u+v
        return nu*nv<=capacity(j)
    return u*v<capacity(j)


def simulate_boundaries(max_A:int=2):
    A=0;u=v=1;k=0;j=1;qcount=0;bcount=0;word=''
    boundaries=[];trace=[];step=0
    while A<=max_A:
        trace.append({'step':step,'A':A,'u':u,'v':v,'k':k,'j':j,'B_count':bcount,'Q_count':qcount,'word':word})
        if can_b(A,u,v,k,j):
            u,v=v,u+v;bcount+=1;word+='B';op='B'
        elif k<6*(2**A)-1:
            k+=1;j+=1;qcount+=1;word+='Q';op='Q'
        else:
            boundaries.append({'A':A,'u':u,'v':v,'k':k,'j':j,'T_A':bcount,'Q_count':qcount,'word':word})
            if A==max_A:break
            A+=1;k=0;j=j_start(A);word+='L';op='L'
        step+=1
        if step>10000:raise RuntimeError('simulation runaway')
    return boundaries,trace


def local_first_domain():
    u=v=1;qmod=0;bcount=0;prefix=''
    rows=[{'prefix_index':0,'primitive':'start','u':u,'v':v,'B_count':bcount,'Q_mod4':qmod,'active_re':1,'active_im':0,'active_den':1,'word_prefix':prefix}]
    for idx,op in enumerate(FIRST_WORD,1):
        if op=='B':u,v=v,u+v;bcount+=1
        elif op=='Q':qmod=(qmod+1)%4
        elif op=='L':pass
        prefix+=op
        re,im=[(1,0),(0,1),(-1,0),(0,-1)][qmod]
        rows.append({'prefix_index':idx,'primitive':op,'u':u,'v':v,'B_count':bcount,'Q_mod4':qmod,'active_re':re,'active_im':im,'active_den':u*v,'word_prefix':prefix})
    return rows


def dump_json(path:Path,obj):
    path.write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--package-root',type=Path,default=Path(__file__).resolve().parents[1]);a=ap.parse_args();root=a.package_root.resolve()
    law=root/f'inputs/{TS}_QBL_PRIMITIVE_CUSTODY_AND_ORTHAD_LAW_v2.md'
    extracts=root/f'inputs/{TS}_SOURCE_AUTHORITY_EXTRACTS.md'
    audit=root/f'inputs/{TS}_p5-b3-v3_AUDIT_RESULTS.md'
    diagram=root/f'inputs/{TS}_orthad-diagram-v5.png'
    required=[law,extracts,audit,diagram,root/'docs/QBL_PRIMARY_PAIRING_TYPE_BOUNDARY_v2.md']
    missing=[str(p) for p in required if not p.exists()]
    if missing:raise SystemExit('missing inputs: '+', '.join(missing))
    law_text=law.read_text();ext_text=extracts.read_text();audit_text=audit.read_text()

    authority_markers={
      'primary generated from retained state and word':'P_t` is the primary pairing generated by the retained state and ordered word' in law_text,
      'chart restrictions derived from primary':'chart restrictions of that pairing' in law_text,
      'directed transfers derived from primary':'directed transfers between the two charts' in law_text,
      'B fixed rank':'matrix rank does not change' in law_text,
      'Q fixed rank':'It does not change the pair or matrix rank' in law_text,
      'L rank extension':'increase the rank of the primary pairing by one' in law_text,
      'old block retained':'preserve the complete old pairing block' in law_text,
      'new orthogonal axis':'append exactly one new active orthogonal axis' in law_text,
      'exact recurrence open':'explicit all-depth recurrence for the primary pairing' in law_text,
      'pullback only intended':'intended algebraic shape' in law_text,
    }
    if not all(authority_markers.values()):
        raise SystemExit('authority marker failure: '+repr({k:v for k,v in authority_markers.items() if not v}))

    # Current authority does not state the complete typing fields.
    absent_type_fields={
      'scalar carrier declared':False,
      'scalar-valued codomain declared':False,
      'linearity declared':False,
      'scalar variance declared':False,
      'symmetry/adjoint law declared':False,
      'left/right/two-sided orthogonality declared':False,
      'complete seed declared':False,
      'complete value recurrence declared':False,
    }
    type_forced=all(absent_type_fields.values())
    if type_forced:raise SystemExit('unexpected: complete type marked forced')

    # Exact local algebra.
    u,v,a_sym=sp.symbols('u v a', nonzero=True)
    b_ratio=sp.simplify((1/(v*(u+v)))/(1/(u*v)))
    if sp.simplify(b_ratio-u/(u+v))!=0:raise SystemExit('B local identity failed')
    if sp.simplify(sp.I*a_sym-sp.I*a_sym)!=0:raise SystemExit('Q local identity failed')

    # Fixed-type rank-one seed uniqueness.
    alpha=sp.symbols('alpha')
    bil_solutions=sp.solve(sp.Eq(alpha,1),alpha)
    sesq_solutions=sp.solve(sp.Eq(alpha,1),alpha)
    if bil_solutions!=[1] or sesq_solutions!=[1]:raise SystemExit('rank-one seed uniqueness failed')

    # Type ambiguity witness under one local normalization.
    bil_seed=sp.Integer(1);sesq_seed=sp.Integer(1)
    bil_i=sp.I;sesq_i=sp.conjugate(sp.I)
    if not (bil_seed==sesq_seed==1 and sp.simplify(bil_i-sesq_i)!=0):raise SystemExit('type witness failed')

    # One-sided orthogonality does not imply two-sided.
    M=sp.Matrix([[1,1],[0,2]])
    left_zero=(M[1,0]==0);right_nonzero=(M[0,1]!=0)
    if not (left_zero and right_nonzero):raise SystemExit('one-sided control failed')

    # Conditional block formula.
    p11,p12,p21,p22,sigma=sp.symbols('p11 p12 p21 p22 sigma')
    P=sp.Matrix([[p11,p12],[p21,p22]])
    E=sp.Matrix([[p11,p12,0],[p21,p22,0],[0,0,sigma]])
    if E[:2,:2]!=P or E[:2,2]!=sp.zeros(2,1) or E[2,:2]!=sp.zeros(1,2):raise SystemExit('conditional block check failed')

    rows=local_first_domain()
    endpoint=rows[-2]  # before L
    if (endpoint['u'],endpoint['v'],endpoint['active_re'],endpoint['active_im'],endpoint['active_den'])!=(55,89,0,1,4895):
        raise SystemExit('first-domain endpoint failed')

    boundaries,custody_trace=simulate_boundaries(2)
    expected=[(0,9),(1,27),(2,61)]
    if [(r['A'],r['T_A']) for r in boundaries]!=expected:raise SystemExit('boundary counts mismatch')
    carry_rows=[]
    for idx in range(1,len(boundaries)):
        cur,prev=boundaries[idx],boundaries[idx-1]
        c=cur['T_A']-2*prev['T_A']
        carry_rows.append({'A':cur['A'],'T_A':cur['T_A'],'T_prev':prev['T_A'],'c_A':c,'recoverable_at_S_A_minus':True,'available_at_previous_instantaneous_L':False})
    if [r['c_A'] for r in carry_rows]!=[9,7]:raise SystemExit('carry indexing failed')

    out=root/'outputs';tr=root/'trace';out.mkdir(exist_ok=True);tr.mkdir(exist_ok=True)
    for p in out.glob(f'{TS}_*'):
        if p.is_file():p.unlink()
    for p in tr.glob(f'{TS}_*'):
        if p.is_file():p.unlink()

    with (out/f'{TS}_first_domain_active_axis_trace.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=list(rows[0].keys()));w.writeheader();w.writerows(rows)
    with (out/f'{TS}_carry_indexing.csv').open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=list(carry_rows[0].keys()));w.writeheader();w.writerows(carry_rows)

    authority={
      'AUTHORITY_FORCED':[
        'one retained generative P_t at every primitive prefix',
        'charts and directed transfers descend from P_t',
        'B and Q preserve architectural rank',
        'L preserves old retained structure and raises rank by one',
        'one new active axis is appended',
        'no projection during mutation'],
      'CANDIDATE_REALIZATION':[
        'P_t : H_t -> D(H_t)',
        'ordinary-dual bilinear scalar model',
        'conjugate-dual sesquilinear scalar model'],
      'OPEN':list(absent_type_fields.keys()),
      'markers':authority_markers,
      'minimality_of_duality_morphism':'NOT_YET_DERIVED'}
    dump_json(out/f'{TS}_authority_boundary.json',authority)

    axiom_fields=[
      {'order':1,'field':'carrier family H_t','depends_on':[]},
      {'order':2,'field':'axis embeddings and rank law','depends_on':[1]},
      {'order':3,'field':'coefficient/scalar system K','depends_on':[1]},
      {'order':4,'field':'pairing codomain V','depends_on':[1,3]},
      {'order':5,'field':'quarter-turn action i','depends_on':[1,3]},
      {'order':6,'field':'pairing kind','depends_on':[1,4]},
      {'order':7,'field':'additivity and linearity','depends_on':[3,4,6]},
      {'order':8,'field':'duality or adjoint operation','depends_on':[3,4,6]},
      {'order':9,'field':'scalar variance','depends_on':[3,7,8]},
      {'order':10,'field':'symmetry or adjoint law','depends_on':[8,9]},
      {'order':11,'field':'orthogonality semantics','depends_on':[6,10]},
      {'order':12,'field':'seed and new-axis normalization','depends_on':[6,9,10,11]},
      {'order':13,'field':'gauge/presentation equivalence','depends_on':[1,3,6,10,12]},
      {'order':14,'field':'B/Q/L complete value mutations','depends_on':list(range(1,14))},
      {'order':15,'field':'chart-interface compatibility','depends_on':[2,8,14]},
    ]
    dump_json(out/f'{TS}_primary_pairing_realization_axiom.json',{'name':'PRIMARY_PAIRING_REALIZATION_AXIOM','fields':axiom_fields,'status':'REQUIRES_RATIFICATION'})

    seed={
      'bilinear_rank_one_fixed_basis':{'general_form':'alpha*x*y','normalization':'P(e,e)=1','solution':'alpha=1','unique':True},
      'sesquilinear_rank_one_fixed_basis':{'general_form':'alpha*conjugate(x)*y','normalization':'P(e,e)=1','solution':'alpha=1','unique':True},
      'type_ambiguity_witness':{'bilinear_at_i_1':'i','sesquilinear_at_i_1':'-i'},
      'same_type_seed_nonuniqueness':'NOT_PROVED',
      'basis_presentation_freedom':'PRESENT',
      'gauge_class_uniqueness':'NOT_YET_DERIVED'}
    dump_json(out/f'{TS}_seed_analysis.json',seed)

    ortho={
      'authority_level_L_signature':['rank +1','old structure embeds unchanged','new active axis appended'],
      'left_orthogonality':'P(new,old)=0',
      'right_orthogonality':'P(old,new)=0',
      'two_sided':'both',
      'counterexample_matrix':[[1,1],[0,2]],
      'counterexample_result':{'left_zero':True,'right_zero':False},
      'conditional_block_formula':'[[P_old,0],[0,sigma]]',
      'status':'TWO_SIDED_ZERO_MIXED_BLOCKS_CONDITIONAL'}
    dump_json(out/f'{TS}_orthogonality_analysis.json',ortho)

    local={'B':'a*u/(u+v)','Q':'i*a','first_domain_endpoint':'i/4895','scope':'LOCAL_ACTIVE_AXIS_ONLY'}
    dump_json(out/f'{TS}_local_descendants.json',local)

    statuses={
      'AUTHORITY_FORCED_PAIRING_FIRST_ARCHITECTURE':'PROVED',
      'MINIMALITY_OF_P_TO_DUAL':'NOT_YET_DERIVED',
      'PRIMARY_PAIRING_REALIZATION_AXIOM':'REQUIRED',
      'EXACT_PRIMARY_PAIRING_TYPE':'NOT_YET_DERIVED',
      'EXACT_PRIMARY_PAIRING_SEED':'NOT_YET_DERIVED',
      'EXACT_PRIMARY_PAIRING_RECURRENCE':'NOT_YET_DERIVED',
      'TWO_SIDED_ZERO_MIXED_L_BLOCKS':'CONDITIONAL_ONLY',
      'HIGHER_ORDER_DESCRIPTIVE_L':'NOT_YET_DERIVED',
      'p5_b3_BRANCH_STATUS':'OPEN'}
    dump_json(out/f'{TS}_status.json',statuses)

    verification={
      'authority_markers':all(authority_markers.values()),
      'complete_type_not_forced':not type_forced,
      'B_local_identity':True,
      'Q_local_identity':True,
      'fixed_type_seed_uniqueness':True,
      'type_ambiguity_model_witness':True,
      'one_sided_orthogonality_counterexample':True,
      'conditional_two_sided_block_formula':True,
      'first_domain_endpoint':True,
      'carry_indexing':True,
      'PROVED_emitted_for_complete_pairing':False}
    if not all(v for k,v in verification.items() if k!='PROVED_emitted_for_complete_pairing') or verification['PROVED_emitted_for_complete_pairing']:
        raise SystemExit('verification dependency failure')
    dump_json(out/f'{TS}_derivation_verification.json',verification)

    with (tr/f'{TS}_authority_decision_trace.jsonl').open('w',encoding='utf-8') as f:
        for key,val in authority_markers.items():f.write(json.dumps({'kind':'authority_marker','claim':key,'present':val},sort_keys=True)+'\n')
        for key,val in absent_type_fields.items():f.write(json.dumps({'kind':'unfixed_type_field','field':key,'fixed':val},sort_keys=True)+'\n')
    with (tr/f'{TS}_local_active_axis_trace.jsonl').open('w',encoding='utf-8') as f:
        for row in rows:f.write(json.dumps(row,sort_keys=True)+'\n')
    with (tr/f'{TS}_axiom_dependency_trace.jsonl').open('w',encoding='utf-8') as f:
        for row in axiom_fields:f.write(json.dumps(row,sort_keys=True)+'\n')
    with (tr/f'{TS}_custody_boundary_trace.jsonl').open('w',encoding='utf-8') as f:
        for row in custody_trace:f.write(json.dumps(row,sort_keys=True)+'\n')
    print(json.dumps({'PASS':True,'first_domain_endpoint':'i/4895','branch_status':'OPEN'},indent=2))

if __name__=='__main__':main()
