#!/usr/bin/env python3
from __future__ import annotations
import argparse, csv, json, re
from fractions import Fraction
from pathlib import Path

TS='20260711T194326'
WORD=list('BQQBBBQBQBBQBBL')


def dump(path,obj):
    path.write_text(json.dumps(obj,indent=2,sort_keys=True)+'\n')


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--package-root',type=Path,default=Path(__file__).resolve().parents[1]);a=ap.parse_args();root=a.package_root.resolve()
    law=(root/'inputs'/f'{TS}_QBL_PRIMITIVE_CUSTODY_AND_ORTHAD_LAW_v2.md').read_text()
    required={
      'pairing_generated':'P_t` is the primary pairing generated by the retained state and ordered word' in law,
      'four_block_shape':all(s in law for s in ['\\Omega_t^+=\\iota_+^*P_t\\iota_+','T_t^{+\\to-}=\\iota_-^*P_t\\iota_+','T_t^{-\\to+}=\\iota_+^*P_t\\iota_-']),
      'shape_is_intended':'The intended algebraic shape is' in law,
      'chart_recurrence_open':'exact chart-map recurrence' in law and 'formalization obligation' in law,
      'B_fixed_rank':'B`: active arithmetic refinement, fixed rank' in law,
      'Q_fixed_rank':'Q`: active phase/orientation mutation, fixed rank' in law,
      'L_preserve_old':'preserve the complete old pairing block' in law,
      'L_append_axis':'append exactly one new active orthogonal axis' in law,
      'L_rank_plus_one':'increase the rank of the primary pairing by one' in law,
      'open_pairing_recurrence':'explicit all-depth recurrence for the primary pairing' in law,
    }
    if not all(required.values()):
        raise SystemExit('missing source dependency: '+json.dumps(required,indent=2))

    interface={
      'arity':2,
      'word_dependent':True,
      'chart_descendants':['++','--','+-','-+'],
      'star_typed':False,
      'architectural_rank_law':'A+1',
      'algebraic_rank_typed':False,
      'source_checks':required,
      'status':'PROVED'
    }
    dump(root/'outputs'/f'{TS}_source_forced_two_slot_interface.json',interface)

    signatures={
      'B':{'rank_change':0,'argument_architecture':'retained','latched':'preserved','active_change':'arithmetic pair metadata','slot_action':'OPEN','value_law':'OPEN','first_missing':'typed active-sector transport under pair refinement'},
      'Q':{'rank_change':0,'argument_architecture':'retained','latched':'preserved','active_change':'quarter-orientation metadata','slot_action':'OPEN','value_law':'OPEN','first_missing':'typed quarter-turn action on two-slot interface'},
      'L':{'rank_change':1,'arity_change':0,'old_old':'embedded prior pairing','old_new':'OPEN','new_old':'OPEN','new_new':'OPEN','zero_mixed_forced':False,'first_missing':'typed orthogonality and extension-component law'},
      'status':'PROVED_AT_ARCHITECTURAL_LEVEL'
    }
    dump(root/'outputs'/f'{TS}_bql_action_signatures.json',signatures)

    # Exact custody and local scalar replay.
    u=v=1; qcount=0; bcount=0; re=Fraction(1); im=Fraction(0); rows=[]; prefix=''
    def scalar_text(re,im):
      if im==0:return str(re)
      if re==0:
        if im==1:return 'i'
        if im==-1:return '-i'
        return f'{im}*i'
      return f'{re}+{im}*i'
    rows.append({'step':0,'op':'start','prefix':'','u':u,'v':v,'B_count':bcount,'Q_count':qcount,'local_re':str(re),'local_im':str(im),'local_scalar':scalar_text(re,im),'formal_pairing':'P[epsilon]'})
    trace=[]
    for step,op in enumerate(WORD,1):
      before=(u,v)
      prefix+=op
      if op=='B':
        factor=Fraction(u,u+v);re*=factor;im*=factor;u,v=v,u+v;bcount+=1
        formal=f'B_{before[0]}_{before[1]}_to_{u}_{v}[P[prefix_{step-1}]]'
      elif op=='Q':
        re,im=-im,re;qcount+=1
        formal=f'Q_{qcount}[P[prefix_{step-1}]]'
      else:
        formal=f'L[P[prefix_{step-1}]]'
      row={'step':step,'op':op,'prefix':prefix,'u':u,'v':v,'B_count':bcount,'Q_count':qcount,'local_re':str(re),'local_im':str(im),'local_scalar':scalar_text(re,im),'formal_pairing':formal}
      rows.append(row);trace.append(row)
    assert (u,v)==(55,89) and bcount==9 and qcount==5 and re==0 and im==Fraction(1,4895)
    with (root/'outputs'/f'{TS}_first_domain_symbolic_trace.csv').open('w',newline='') as f:
      w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
    with (root/'trace'/f'{TS}_symbolic_prefix_trace.jsonl').open('w') as f:
      for r in rows:f.write(json.dumps(r,sort_keys=True)+'\n')

    l_schema={'argument1':['old','new'],'argument2':['old','new'],'components':{'old_old':'Emb(P_t)','old_new':'OPEN','new_old':'OPEN','new_new':'OPEN'},'forced_zero_components':[],'architectural_rank_increment':1,'pairing_arity':2,'status':'PROVED_BOUNDARY'}
    dump(root/'outputs'/f'{TS}_L_component_schema.json',l_schema)

    # Nonsymmetric one-sided orthogonality control.
    matrix=[[1,1],[0,2]]
    control={'matrix':matrix,'new_old':matrix[1][0],'old_new':matrix[0][1],'one_sided_zero':matrix[1][0]==0,'other_mixed_nonzero':matrix[0][1]!=0,'verdict':'COUNTERMODEL: one-sided orthogonality does not force both mixed components zero'}
    if not (control['one_sided_zero'] and control['other_mixed_nonzero']):raise SystemExit('control failed')
    dump(root/'outputs'/f'{TS}_one_sided_orthogonality_control.json',control)

    candidates=[
      ['nonrepresented two-slot pairing','yes','yes','argument category and abstract restriction','MODEL WITNESS','not selected'],
      ['represented duality morphism','yes','yes','duality, embeddings, naturality','MODEL WITNESS','not selected'],
      ['scalar bilinear','yes','yes','module, scalars, bilinearity','MODEL WITNESS','not selected'],
      ['conjugate sesquilinear','yes','yes','involution, variance, adjoint','MODEL WITNESS','not selected'],
    ]
    with (root/'outputs'/f'{TS}_realization_candidates.csv').open('w',newline='') as f:
      w=csv.writer(f);w.writerow(['candidate','two_slots','four_blocks','extra_data','evidence_class','authority_selection']);w.writerows(candidates)

    # Same custody cocycle, two arbitrary class sequences: cocycle alone cannot determine class dynamics.
    carries=[9,7,8,8,9,8,7,8]
    class_a=['x']*len(carries)
    class_b=[f'y{i%3}' for i in range(len(carries))]
    boundary={'same_carry_sequence':carries,'pairing_class_model_A':class_a,'pairing_class_model_B':class_b,'different_classes':class_a!=class_b,'current_linking_equation_present':False,'status':'OPEN','first_missing_bridge':'exact boundary-return law or quotient map on primary-pairing classes'}
    dump(root/'outputs'/f'{TS}_boundary_return_pairing_constraint.json',boundary)

    statuses={
      'SOURCE_FORCED_TWO_SLOT_PAIRING_INTERFACE':'DERIVED',
      'ORTHAD_LEVEL_BQL_SIGNATURES':'DERIVED_AT_ARCHITECTURAL_LEVEL',
      'EXACT_PRIMARY_PAIRING_RECURRENCE':'NOT_YET_DERIVED',
      'PAIRING_SIMPLIFICATION_FROM_EFFECTIVE_INVARIANTS':'NOT_YET_DERIVED',
      'D1_DOMAIN_PROPER_EFFECTIVE_INVARIANT':'NOT_YET_DERIVED',
      'HIGHER_ORDER_DESCRIPTIVE_L':'NOT_YET_DERIVED',
      'BRANCH_STATUS':'OPEN'
    }
    dump(root/'outputs'/f'{TS}_status.json',statuses)

    checks={'source_dependencies':all(required.values()),'trace_endpoint':im==Fraction(1,4895),'two_slot_arity':interface['arity']==2,'L_old_old_preserved':l_schema['components']['old_old']=='Emb(P_t)','no_unlicensed_zero_blocks':len(l_schema['forced_zero_components'])==0,'boundary_bridge_not_invented':not boundary['current_linking_equation_present']}
    if not all(checks.values()):raise SystemExit('derivation checks failed')
    dump(root/'outputs'/f'{TS}_derivation_verification.json',{'checks':checks,'all_pass':True})

    with (root/'trace'/f'{TS}_authority_decision_trace.jsonl').open('w') as f:
      for k,v in required.items():f.write(json.dumps({'claim':k,'source_present':v},sort_keys=True)+'\n')
      for op,data in signatures.items():
        if op!='status':f.write(json.dumps({'operation':op,'signature':data},sort_keys=True)+'\n')
    with (root/'trace'/f'{TS}_model_witness_trace.jsonl').open('w') as f:
      f.write(json.dumps(control,sort_keys=True)+'\n')
      f.write(json.dumps(boundary,sort_keys=True)+'\n')
    print(json.dumps({'PROVED':True,'rows':len(rows),'endpoint':'i/4895','branch_status':'OPEN'},indent=2))

if __name__=='__main__':main()
